# Generated by Django 5.0.5 on 2024-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Kurs nomi')),
                ('about', models.TextField(verbose_name='Kurs haqida')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Kurs Rasmi ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kurs narxi')),
                ('rating', models.IntegerField(max_length=5, verbose_name='Kursni baholash uchun')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('duration', models.DurationField(verbose_name='Kurs davomiyligi ')),
                ('modules', models.CharField(max_length=50, verbose_name='Kurs modullari')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurs',
                'db_table': 'CoursePost',
                'managed': True,
            },
        ),
    ]
