# Generated by Django 5.0.5 on 2024-05-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_coursepost_duration_alter_coursepost_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepost',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Kurs narxi'),
        ),
    ]
