# Generated by Django 5.0.5 on 2024-05-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_coursepost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepost',
            name='rating',
        ),
    ]
