# Generated by Django 5.0.5 on 2024-05-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_coursepost_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachersPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Ustozning ismi')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Ustozning rasmi')),
                ('level', models.CharField(max_length=50, verbose_name='Ustozning darajasi')),
                ('about', models.CharField(max_length=300, verbose_name='Ustoz haqida')),
            ],
            options={
                'verbose_name': 'Ustoz Haqida Post',
                'verbose_name_plural': 'Ustoz Haqida Posts',
                'db_table': 'TeacherPost',
                'managed': True,
            },
        ),
    ]
