# Generated by Django 5.0.5 on 2024-05-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_teacherspost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Izoh qoldiruvchining ismi')),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Izoh Rasmi')),
                ('level', models.CharField(max_length=50, verbose_name='Izoh qoldiruvchining mansabi')),
                ('about', models.TextField(verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Izoh ',
                'verbose_name_plural': 'Izoh s',
                'db_table': 'ReviewPost',
                'managed': True,
            },
        ),
    ]
