# Generated by Django 5.0.5 on 2024-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_reviewpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewpost',
            options={'managed': True, 'verbose_name': 'Izoh ', 'verbose_name_plural': 'Izohlar'},
        ),
    ]
