# Generated by Django 5.0.5 on 2024-05-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(default='mo', max_length=50)),
                ('certificates', models.BooleanField(default=True)),
                ('full_courses', models.BooleanField(default=True)),
                ('full_modules', models.BooleanField(default=True)),
                ('live_projects', models.BooleanField(default=True)),
                ('support', models.CharField(default='24 x 7 supports', max_length=100)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'Plan',
                'managed': True,
            },
        ),
    ]
