# Generated by Django 5.0.5 on 2024-05-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.CharField(default='month', max_length=50),
        ),
    ]
