# Generated by Django 5.0.5 on 2024-05-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_contactpage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='message',
            field=models.TextField(),
        ),
    ]
